name: Git bisect
on:
  workflow_dispatch:
    inputs:
      first_commit:
        description: "Commit hash"
        required: true
        type: string
      second_commit:
        description: "Commit hash"
        required: true
        type: string

jobs:
  build_app:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        env:
          GH_TOKEN_DISPATCH_ACTION: ${{ secrets.GH_TOKEN_DISPATCH_ACTION }}
        run: |
          git clone https://github.com/facebook/react-native.git
          cd react-native
          git log --reverse ${{inputs.first_commit}}^...${{inputs.second_commit}} --pretty=format:"%h" | while read commit; do
            echo "Triggering build for $commit..."
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GH_TOKEN_DISPATCH_ACTION"\
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/almouro/react-native-flashlight-tests/actions/workflows/bisect.yaml/dispatches \
              -d "{\"ref\":\"main\", \"inputs\":{\"commit\":\"$commit\"}}"
          done
