name: Build for untested RN versions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 2-5" # Runs at 1 AM (UTC) every day except Saturday, Sunday and Monday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Yarn
        run: npm install -g yarn

      - name: install dependencies
        run: yarn

      - name: Run dailyBuild.ts
        run: npx ts-node ./dailyBuild/dailyBuild.ts
        env:
          GH_TOKEN_DISPATCH_ACTION: ${{ secrets.GH_TOKEN_DISPATCH_ACTION }}
